#pragma once
#define USB_SUSPEND_WAKEUP_DELAY 200

#define MATRIX_ROW_PINS_RIGHT {GP9, GP8, GP7, GP6, GP5}
#define MATRIX_COL_PINS_RIGHT {GP15, GP14, GP13, GP12, GP11, GP10}

#define OS_DETECTION_KEYBOARD_RESET
#define OS_DETECTION_DEBOUNCE 250
#define OS_DETECTION_SINGLE_REPORT
#define ONESHOT_TIMEOUT 500
#define TAPPING_TERM 140
#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

#define EE_HANDS // Store which side I am in EEPROM
/* Reset */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
